# Generated by Django 3.0.6 on 2020-05-31 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_group_groupmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=models.SET(-1), related_name='paid_by', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(on_delete=models.SET(-1), related_name='paid_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=150)),
                ('money', models.FloatField()),
                ('added_by', models.ForeignKey(on_delete=models.SET(-1), related_name='expense_by_me', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=models.SET(-1), related_name='expenses', to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=150)),
                ('money', models.FloatField()),
                ('is_returned', models.BooleanField(default=False)),
                ('date_given', models.DateField(default='1900-01-01')),
                ('entry_added', models.DateTimeField(auto_now_add=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_by', to=settings.AUTH_USER_MODEL)),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
